export enum CountriesEnum {
    Austria = 'austria',
    Australia = 'australia',
    Azerbaijan = 'azerbaijan',
    Albania = 'albania',
    Algeria = 'algeria',
    AmericanSamoa = 'c',
    Anguilla = 'anguilla',
    England = 'england',
    Angola = 'angola',
    Andorra = 'andorra',
    Antigua = 'antigua',
    Argentina = 'argentina',
    Armenia = 'armenia',
    Afghanistan = 'afghanistan',
}
